### ISSUE TITLE
Improve Qt MOC compilation time

### ISSUE THREAD

**Issue by dgehri** [arximboldi/lager#108]
The Qt MOC compiler is notoriously slow when preprocessing. 

In particular, each time code includes _lager/extra/qt.hpp_, the MOC compiler spends about four seconds on precompiling it, even though the Qt relevant code is less than 100 lines.

Simply excluding non-Qt relevant code in _lager/extra/qt.hpp_ as follows would reduce MOC processing time to a fraction of a second:

```
#ifndef Q_MOC_RUN
#include <lager/cursor.hpp>
#include <lager/reader.hpp>
#include <lager/watch.hpp>
#endif
```

**Comment by arximboldi** [comment]
Thanks for the fix!
