### ISSUE TITLE
Q: Can lager be used for Incremental Computation aka Self Adjusting Computations ?

### ISSUE THREAD

**Issue by lenkite** [arximboldi/lager#119]
Hi, this may be a dumb question, but can lager do stuff like what https://github.com/salsa-rs/salsa can do ? Can it memoize ?

**Comment by arximboldi** [comment]
I think Cursors can solve part of the problem. Watch the `Squaring the circle` talk for details. The dynamic key-based data-base you would have to build on top. I have done something like that in a private project for a client, maybe one day that could reach the public repo but it would need some cleaning up.
