### ISSUE TITLE
How should coeffects be handled?

### ISSUE THREAD

**Issue by danielytics** [arximboldi/lager#120]
The documentation on reducers states that reducers must be referentially transparent and pure functions. How should coeffects be handled?

For example, if my action required a random number, or the current time, how can I pass this into the update function? Given that lager calls the function for me and I don't see any functionality for injecting impure data into it as an argument, the only two ways  I can think of are:

1. Wrapping the actions. Eg if I have `my_action` then I instead pass `wrapper_with_coeffects<my_action>` or `std::tuple<my_action, my_coeffects>` or something similar as the action. Then I would have be create this object before calling the store's `dispatch` function.
2. Write the data to the model before dispatching the action, I guess by dispatching coeffect actions. So every time I want to call `store.dispatch`, I'd actually call it twice: once with `set_coeffects_action` and then right after with the actual action I want to dispatch, eg `my_action`.

The benefit of 2. is that as far as actions are concerned, all state is in the model and the reducers just concern themselves of the actual action and the model, not some odd wrapped action.

Both have the disadvantage that I can't dispatch actions directly, but need to make a wrapper function that does the extra work. Not a problem for me since I hide much of the Lager API behind a wrapper anyway (so that I can manage lifecycle, multi threading/managing actors, etc).

Is this the expected way to do this or is there some tool built in that I'm missing?

**Comment by arximboldi** [comment]
Have you looked at the effects section of the documentation?
https://sinusoid.es/lager/effects.html

One common pattern is to divide your action in two:
```c++
struct some_action { ...; };
struct some_action_with_timestamp{ std::chrono::steady_clock::time_point ts; };
```
The reducer of `some_action` returns an effect like:
```c++
[a](auto&& ctx) {
    ctx.dispatch(some_action_with_timestamp{
        std::chrono::steady_clock::now(),
        ...
    });
};
```

**Comment by danielytics** [comment]
> Have you looked at the effects section of the documentation?

Of course, but unless I'm missing something, it only shows how to output effectful things, not how to input them. I suppose the relevant part you're highlighting here is the ability to dispatch from an effect handler (and that this can be done inline in the update function in a lambda. Cool.

So just to make sure I understand the pattern that you're describing: when `some_action` is dispatched, it gets handled by issuing an effect that then issues a version of the action that includes the extra data?

I suppose the advantage of this is that the externally visible API is just dispatching the action to the store, as if there was no coeffect data, which is nice. With the downside that the actions need to be split, but maybe I can hide much of this by composing them. 

Thanks for the input, that gives me another approach to think about.

**Comment by arximboldi** [comment]
I must admit I am finding this notion of "effectful input" interesting. My proposed solution has some caveats...  I'm gonna give it a thought to see if there is some API we can add for this explicitly. Feel free to sketch here what you think would be convenient for your use-cases.

**Comment by danielytics** [comment]
Great, thanks!

I think re-frame is a good rolemodel to use for ideas: https://day8.github.io/re-frame/Coeffects/

Basically, how they work there is when you register the event handler, you specify the "coeffect", which then gets passed to the handler as an argument:

```clj
(rf/reg-event-fx
  :some-id
  [(rf/inject-cofx :random-int 10) (inject-cofx :now)]
  (fn [{:keys [now random-int db]} _]
    ...))
```

In re-frame, the model (`db`) is itself just a coeffect that is included by default. I'm not sure if that would make sense in lager, which would then look something like `void(ModelWithCoeffects, Action)`, or `void(std::tuple<Model,Coffect1,Coeffect2>, Action)` or perhaps `void(std::pair<Model,Coeffects>, Action)`. An alternative is that each coeffect gets added as a new argument: `void(Model, Coeffect1, Coeffect2, Action)`.

In re-frame, the coeffect is registered to some global registry of coeffects, so :random-int names a function that was earlier registered.

I'm not really sure right now how this should work in lager. I guess it makes sense to provide the possible coeffects as template arguments the same way as you do for effects. How you should decide that an action requires a coeffect though? I'm unsure.

As for how to receive them, I kinda like the tuple, although perhaps as a separate argument from the model. Something like `void(Model, Action, std::tuple<CoEffect1, CoEffect2>)`.

But I don't have any strong opinions nor am I leaning towards any particular implementation or API, right now I'm just not familiar or comfortable enough with Lager yet to really be able to give any good input on it. I'm still learning how to use it properly and the best way to structure things, so I fell any thoughts I give now are based on incomplete understanding of Lager still.

**Comment by danielytics** [comment]
For now, I'm going to either use your suggested approach, or I will simply wrap the dispatch function, and then later I will refactor. I want to just get things working for now and I feel I'll be doing some major refactoring anyway as I get more comfortable with Lager, eg to better decompose my code into a nice modular approach, better use of cursors etc, so at that point I might also have a better feel for how I'm using coeffects.

As an unrelated aside, maybe I should open a new issues but I'm wary of spamming your issue tracker with questions. I'm trying to understand how to properly use cursors and lenses and I'm struggling a little with one particular case:

Lets say I have a model "house" and it has an immer vector of rooms and each room has carpet, if I want to update the carpet in each room, how would I do that? From what I understand of lenses, I can access individual rooms by index, but to update each room I'd have to do two separate updates: in clojure code that would be something like

```clj
(update-in model path-to-rooms (fn [rooms] (map rooms #(update-in % path-to-carpet update-fn))))
```

Which in lager seems to map to a calling `over` with a lens to the rooms vector, then in the update function loop/accumulate over each room and calling `over` with a lens into the room to update the carpet. Does that sound more or less correct? 

I assume something like [Specter](https://github.com/redplanetlabs/specter)'s `transform` isn't easily possible.

**Comment by arximboldi** [comment]
@Siapran I think maybe you did develop some lens to cover that particular case, is this true?

**Comment by Siapran** [comment]
yeah this would require a generalized `map` lens transformers. right now all we have is `map_opt` and `bind_opt`, but what they'd need is a `map_seq`.

I can make something like that if you think it'd be useful as a stopgap until I rework all the lens stuff.
