### ISSUE TITLE
Watch the result of a zoom?

### ISSUE THREAD

**Issue by kevin--** [arximboldi/lager#125]
Seems relatively obvious, but cannot get it working (fails to compile...maybe not supported?)

```
    auto view = mStore.zoom( lager::lenses::attr( &model::member ) );
    lager::watch( view, []( auto )
    {
        std::cout << "member changed!\n";
    } );
```

**Comment by Siapran** [comment]
you need to add `.make()` at the end of the zoomed expression, or assign the expression to an actual cursor/reader type instead of `auto`.

**Comment by kevin--** [comment]
sorry to reopen; as @Siapran suggests that works to compile, thanks.
However I do not get any callbacks on watched zooms.

For example, my setup is like this:
```
struct Model
{
    int value = 0;
};

mStore = lager::make_store<Action>( Model{}, lager::with_manual_event_loop() );

auto tracksView = mStore.zoom( lager::lenses::attr( &model::value ) ).make();
lager::watch( tracksView, []( auto )
{
    // never called
} );

lager::watch( mStore, []( auto )
{
    // called
} );

mStore.dispatch( Increment{} );
```

**Comment by arximboldi** [comment]
That's probably because `tracksView` gets out of scope and is destructed. Note that the watchers are local to the C++ *object* in which they are are applied. This is useful in many practical scenarios but seems to be a recurring pitfall for newcomers. I should really tweak the API...

**Comment by arximboldi** [comment]
The solution in this case to keep the result in a `lager::reader<int>` whose lifetime is as long as the lifetime of the callbacks. For example, you may have something like this:

```
class ModelView {
  lager::reader<int> value_;
public:
  ModelView(lager::reader<Model> model)
     : value_{ model.zoom(lager::lenses::attr( &model::value )) }
  {
    value_.watch([] (auto v){
      // this will be called
    });
  }
};

// somewhere in your application you instantiate this ModelView...
```

Note that the current behavior makes it easier to make statefuil UI components in this style with the callbacks having just the right lifetime (the lifetime of the local reader).

Btw, one note: `reader.zoom( lager::lenses::attr( &model::value ) )` is equivalent to `reader[lager::lenses::attr( &model::value ) ]` and to `reader[&model::value]` for terser syntax.

**Comment by kevin--** [comment]
> That's probably because `tracksView` gets out of scope and is destructed. Note that the watchers are local to the C++ _object_ in which they are are applied. This is useful in many practical scenarios but seems to be a recurring pitfall for newcomers. I should really tweak the API...

good call ok -- my mistake

**Comment by arximboldi** [comment]
No worries, I know this is super confusing!
