### ISSUE TITLE
Issue with notifications from lager::state

### ISSUE THREAD

**Issue by dimula73** [arximboldi/lager#135]
Hi!

I have a weird issue with notifications from lager::state<>. For some reason, the state doesn't emit any notifications, but if I wrap it into a cursor, then the notifications work fine. If I do `state.nudge()`, then the notifications arrive fine, but when I change the contents of the state using cursors to its members, the state keeps silence.

I tries to reproduce the issue in a unittest, but failed. In unittest it works fine, but not in my real code. I'm still not sure this bug is in lager itself or in my code. Could you suggest me any direction, where I should look at? Or at least how to debug the issue?

```cpp
#include <boost/operators.hpp>

namespace testns {
struct Child : public boost::equality_comparable<Child>
{
    friend bool operator==(const Child &lhs, const Child &rhs) {
        return lhs.childValue == rhs.childValue;
    }

    Child() = default;
    Child(int value) : childValue(value) {}

    int childValue = 0;
};

struct Parent : public boost::equality_comparable<Parent>
{
    friend bool operator==(const Parent &lhs, const Parent &rhs) {
        return lhs.parentValue == rhs.parentValue &&
            lhs.child == rhs.child;
    }

    int parentValue = 0;
    Child child;
};
}

TEST_CASE("state, check notifications come after edits through a cursor")
{

    lager::state<testns::Parent, automatic_tag> state;
    lager::cursor<testns::Parent> intermCursor = state;
    lager::cursor<testns::Child> childCursor = intermCursor[&testns::Parent::child];
    lager::cursor<int> childValueCursor = childCursor[&testns::Child::childValue];

    auto childSpy = testing::spy([&](const testns::Child &value) {
        CHECK(value.childValue == 13);
    });

    auto parentSpy = testing::spy([&](const testns::Parent &value) {
        CHECK(value.parentValue == 0);
        CHECK(value.child.childValue == 13);
    });

    watch(state, parentSpy);
    watch(childCursor, childSpy);

    //childCursor.set(testns::Child(13));
    childValueCursor.set(13);

    CHECK(state.get().parentValue == 0);
    CHECK(state.get().child.childValue == 13);

    CHECK(childSpy.count() == 1);

    /// HERE!!! In real code, parent doesn't emit anything, but in this unittest the signal works fine
    CHECK(parentSpy.count() == 1);
}

```

**Comment by dimula73** [comment]
Here is the unittest in a form of a patch: https://invent.kde.org/-/snippets/2082

Again, this unittest works fine, but "the same construction" in real code not.

Though real structures are much heavier: https://invent.kde.org/dkazakov/krita/-/blob/kazakov/lager-based-brush-editor/libs/brush/KisBrushModel.h#L140

**Comment by dimula73** [comment]
Okay, I have found the reason of the issue. The problem happened because of a code that does 

```cpp
state = testns::Parent();
```

that implicitly creates a new state and removes the previous one.

I'll make a patch to remove the faulty assignment operators...

**Comment by dimula73** [comment]
Hi, @arximboldi!

As far as I understand, move-assign should be prohibited by this line:

```
state& operator=(T&&) = delete;
```

I have briefly tested it and it seems to be prohibited.

Ideally, it would be nice is all the cursor-like objects to supported dereferencing operator, so that the following would be a valid code:

```
*state = TestNS::Parent()
```

That resembles the concept implemented in `std::optional`. And it would make the current implementation of `operator->` for lager cursors a bit more consistent.

**Comment by dimula73** [comment]
One more confusing note. Const-dereference is also allowed:

```cpp
value = *state;
```

**Comment by arximboldi** [comment]
Oh I see! I got confused, so you are prohibitting assignment from `T`, but from `state&&` itself it's fine (https://github.com/arximboldi/lager/blob/46307712e30de39a7facab17fa624010395734ab/lager/state.hpp#L95-L96). This all sounds good to me. Thank you for investigating this! :+1:
