### ISSUE TITLE
Lenses on a store with_debugger?

### ISSUE THREAD

**Issue by kevin--** [arximboldi/lager#139]
Been working on an app based on Lager for a bit now, and have many places where the GUI is taking readers on the model, for example:
```
struct Model
{
    int x;
};

...
// client
lager::reader<int> getXReader()
{
    return mStore[&Model::x];
}
```

This all works great.

Now we want to add some undo/redo/history based on the `with_debugger` enhancer you've shown in the example. Trivially, we add `with_debugger()` as a store enhancer. This changes the type of the store... great, but now how do we construct a reader against the store that will also update if the history cursor changes?

I see the conversion operator to Model as well as the `friend unwrap()`, which feels close, but I'm clearly missing a step to reimplement `getXReader` from the example.
```
lager::reader<int> getXReader()
{
    return mStore[/* what goes here? */][&Model::x];
}
```

Can you point me in the right direction? Thanks

**Comment by TheCoconutChef** [comment]
@kevin-- This is rather timely. I had the same issue last week: https://github.com/arximboldi/lager/issues/137

**Comment by arximboldi** [comment]
Thanks @TheCoconutChef for chiming in!

**Comment by kevin--** [comment]
many thanks this works great 🙏  @TheCoconutChef
