### ISSUE TITLE
Lager library has no official releases

### ISSUE THREAD

**Issue by dimula73** [arximboldi/lager#175]
Lager (as well as immer and zug) have no official releases. It makes it impossible to package them by distributions. Are there any plans to release them officially?

My lager-based code has been officially merged into Krita recently, so the distributions are now interested in packaging lager as well.

**Comment by arximboldi** [comment]
Thank you @dimula73 for bringing attention to it. Most Lager projects that I am aware of have been applying a "live at head" kind of philosophy and therefore this has been low priority on my list. But it should be addressed. I will actually try get this done this week.

Also congratulations on the Krita - Lager work! It's an honour that the library is used in such an amazing project! :clap: :pray:

**Comment by dimula73** [comment]
Thank you for warm words! :)

There might be a small problem: in Krita we use the version with this bug fixed https://github.com/arximboldi/lager/issues/160 (using my PR https://github.com/arximboldi/lager/pull/165).

And the problem with this MR is that it might change lager's API a little bit (due to a rewrite of everything using lager::getset). How could we handle that?

**Comment by dimula73** [comment]
Hi, @arximboldi!

Thank you very much for the release! Could you also add released for immer and zug? I see that immer has a release, but zug still hasn't any.

**Comment by arximboldi** [comment]
Done :)

**Comment by dimula73** [comment]
Thanks a lot! :)
