### ISSUE TITLE
Missing <memory> include

### ISSUE THREAD

**Issue by Louis-Simon22** [arximboldi/lager#18]
I have to `#include <memory>`  before including lager for it to work. The other way around doesnt work. Maybe you're missing an `#include <memory>` in `context.hpp`?
```
#include <iostream>
#include <lager/store.hpp>
#include <memory>

int main(int argc, char **argv) {
  std::cout << "Hello, world!" << std::endl;
  return 0;
}
```

**Comment by arximboldi** [comment]
Aha, thanks! :smile:
