### ISSUE TITLE
Abstract dependencies with effects

### ISSUE THREAD

**Issue by leonp-s** [arximboldi/lager#188]
I am currently trying to figure out how to use abstract dependencies as deps to effects (and if this is possible / a good idea...), take for example,

``` cpp
struct Base {
    virtual ~Base() = default;
    virtual bool Load() = 0;
}

using Effect = lager::effect<Action, lager::deps<Base *>>;

```

this results in the following error,

```
no viable conversion from returned value of type 'std::pair<Model, lager::effect<std::variant<... Actions>, lager::deps<Base *>>>' to function return type 'std::decay_t<const Model &>' (aka 'Model')
        return new_model;

```

having read though the docs on effects I am struggling to understand why this might be an issue, any help would be really appreciated.

**Comment by arximboldi** [comment]
I think that should really be fine. Can you show me the rest of the code?

I use abstract dependencies often. When I do, I don't use `Base*` but `Base&`. Either way, I don't think there is anything that should prevent the pointer from working. Maybe the mistake is somewhere else?

**Comment by arximboldi** [comment]
I think the problem is in the implementation of `UpdateTabs`, you are probably doing `return new_model` instead of `return {new_model, lager::noop}`, or even better return `lager::result` instead of `std::pair`...

**Comment by leonp-s** [comment]
Hi, thanks again for the response. Things appear to be resolved when using the following,

``` cpp
lager::with_deps (
                std::reference_wrapper<TabsControllerDelegate> (tabs_controller_delegate_mock))
```

**Comment by arximboldi** [comment]
I do not think that's the issue, as that's equivalent to using `std::ref` like in your example above.
