### ISSUE TITLE
Implement lenses for std::tuple, std::variant and std::optional

### ISSUE THREAD

**Issue by Siapran** [arximboldi/lager#30]
It would be nice to access the Nth element of a tuple (std::get), the Nth type of a variant (also std::get), and the only element of a std::optional.

It would also be nice to have cursors return an optional (or throw?) if the underlying part of the view is not present (out of bounds for collections and tuples, bad variant access, nothing in optional).

**Comment by arximboldi** [comment]
Yes, all those lenses and cursors transformations are indeed useful and may be added soon. Thanks! :+1:

**Comment by Siapran** [comment]
I need to sort out licensing with my managers but I have a working solution for handling unfocused lenses using optionals: [sample unit tests](https://gist.github.com/Siapran/14746713c808133ba806807ba421c7b9)

**Comment by Siapran** [comment]
got an answer on licensing. I'll submit a PR for review soon.

**Comment by arximboldi** [comment]
Awesome! Those tests are looking good, I like that approach. Looking forward to look at that code :slightly_smiling_face:

**Comment by Siapran** [comment]
I'm trying to make a smart lens for automatically lifting anything that doesn't handle optionals, but I'm having trouble detecting this properly:
```cpp
struct functor_wrapper_t {
    template <typename T>
    const_functor<T> operator()(T&& t) const noexcept;
};

template <typename Lens, typename T>
using viewed_t = decltype(
    std::declval<Lens>()(functor_wrapper_t{})(std::declval<T>()).value);

template <typename T>
struct smart_lens<std::optional<T>>
{
    template <typename U>
    static auto make(U &&u) {
        // don't lift lenses that can already handle optionals
        if constexpr (zug::meta::is_detected<viewed_t, U, std::optional<T>>::value) {
            return LAGER_FWD(u);
        } else {
            return ::lager::lens::optlift(smart_lens<T>::make(std::forward<U>(u)));
        }
    }
};
```
```cpp
TEST_CASE("zooming, unfocused")
{
    state<std::vector<person>> st{{person{{5, 4}, "juanpe"}}};
    auto p  = st[0];
    auto n1 = p[&person::name];
//    auto n2 = p[lens::attr(&person::name)]; // detected as able to handle optional
    auto n3 = p[lens::fallback(person{{1, 1}, "NULL"})];
    auto n4 = p[lens::optlift(lens::attr(&person::name))];
}
```
I might need some help to finish implementing this...

**Comment by arximboldi** [comment]
You did this, hero! @Siapran
