### ISSUE TITLE
Zoom available as a method for cursor.

### ISSUE THREAD

**Issue by Siapran** [arximboldi/lager#31]
In [this slide](https://sinusoid.es/talks/meetingcpp19/#/41), you introduce a `zoom(lens)` method on cursors, before replacing it with the `operator[]` syntax.
Currently, in Lager, zoom is only available as a free function, which is fine, until you reach this kind of situation:
```
LAGER_QT(imagePath){zoom(boxLens, data
                    [&VolumeTree::children][index]
                    [&VolumeVolumeRegistration::tree])
                    [&VolumeTree::volume][&Volume::name]
                .xf(stdToQtStrMapper)}
```
Not having an infix solution for zooming makes this kind of construct a bit cumbersome.

**Comment by arximboldi** [comment]
You are right, this should be fixed. Thanks!

**Comment by Siapran** [comment]
so, I was able to make the `cursor[lens]` syntax work with:
```cpp
template <typename T, typename Key>
using at_t = std::decay_t<decltype(std::declval<T>().at(std::declval<Key>()))>;

template <typename T>
struct smart_lens_base
{
    template <typename Lens, std::enable_if_t<!zug::meta::is_detected<at_t, T, Lens>::value, int> = 0>
    static auto make(Lens l)
    {
        return l;
    }

    template <typename Key, std::enable_if_t<zug::meta::is_detected<at_t, T, Key>::value, int> = 0>
    static auto make(Key k)
    {
        return lens::at(std::move(k));
    }

// ...
```
which, admittedly, might not be the best way to do it.
it was either that or checking if `zoom(lens, *this)` was detected inside `operator[]`.

**Comment by arximboldi** [comment]
Nice. I like the idea of being able to pass a less directly to `[]` and have been flirting with it for a while. May implement it soon...

**Comment by arximboldi** [comment]
Fixed.
