### ISSUE TITLE
states/cursors vs store/readers/actions

### ISSUE THREAD

**Issue by Siapran** [arximboldi/lager#32]
If I understand correctly, the store only allows the use of actions/reducers and readers, which makes the use of cursors somewhat complicated.
It feels like you have to chose either using the store and the full unidirectional architecture, or using cursors to integrate easily with existing OO code.
Am I understanding this correctly, and if so, which approach would you recommend?

**Comment by arximboldi** [comment]
The `store` exposes the current state as a reader cursor. That allows for a hybrid approach: you use actions to perform mutations, but cursors bind the underlying model to objecty reactive properties (e.g. QObject Q_PROPERTY). This is actually my favourite way of using it in my current QML projects. (I still use writable cursors outside of the redux like store for some stuff, like parts of the view state.)
