### ISSUE TITLE
Watching a default constructed cursor causes the default constructed pointer to node to be deferenced.

### ISSUE THREAD

**Issue by Siapran** [arximboldi/lager#34]
see:
[default constructor of `reader_base`](https://github.com/arximboldi/lager/blob/master/lager/reader.hpp#L80)
[calling `->observers()` on a `nullptr`](https://github.com/arximboldi/lager/blob/master/lager/watch.hpp#L49)

**Comment by Siapran** [comment]
This happens if you use the `LAGER_QT_READER` macro and forget to initialize the reader in the constructor.
Is there any reason we need to allow default constructing cursors?

**Comment by arximboldi** [comment]
Yes, I've noticed this recently. I wanna keep allowing default-constructed cursors. I think it make sense to be able to associated a watched to default-initialized cursor, and then later dynamically change the source of the data (maybe multiple times).

**Comment by smantzavinos** [comment]
I would like to resurface some arguments for this issue. In particular, the issue I'm concerned with is using the LAGER_QT_READER in the header in conjunction with the LAGER_QT macro in the member initializer list. 

As @Siapran stated, if you use the LAGER_QT_READER macro but did not define the LAGER_QT macro, there is no compile time issue, but instead a crash at runtime. 

Obviously there are very different mechanisms at play, but I view this the same as declaring a function and then forgetting to define it. As such, I would expect a compile time issue for the missing definition.

I see that there are good reasons that this currently doesn't happen, but I am losing a huge compile time guarantee. One of the reasons we use a strongly typed language is for the compile time checks. I feel like I am currently missing one of those basic checks.

I don't know enough about the library to have any suggestions for a fix, but I hope you agree that this is an important compile time safety check.

**Comment by arximboldi** [comment]
Hi @smantzavinos! Now there is no crash at runtime anymore, simply no data is propagated. I think this is enough for now. The compilation error could be introduced by disabling default construction of cursors. Maybe that is a good idea, but I am not a hundred percent sure...

**Comment by Siapran** [comment]
Maybe we could mark default constructors as deprecated so that it at least shows up as a warning at compile time?

**Comment by arximboldi** [comment]
Not sure I want to deprectate it. Either we allow the behavior or we don't.
