### ISSUE TITLE
library conflicts when building from nix-shell

### ISSUE THREAD

**Issue by Siapran** [arximboldi/lager#38]
see logs [here](https://gist.github.com/Siapran/cbb728ba1f8bebfd7acab4b4d04d290b).
this is from a fresh clone and a fresh nix installation.

**Comment by arximboldi** [comment]
Which distro is this? I suspect you may workaround with `nix-shell --pure`

**Comment by Siapran** [comment]
Manjaro linux (4.19.107-1-MANJARO).
`nix-shell --pure` seems to work, thanks :+1:

**Comment by arximboldi** [comment]
Nice! :+1:
