### ISSUE TITLE
clang format

### ISSUE THREAD

**Issue by ltjax** [arximboldi/lager#4]
Using clang format would be nice to get all formatting problems out of the way.

**Comment by arximboldi** [comment]
Hahaha, yeah I've been wanting to create a `clang-format` that I like for ages but always was too lazy... this is a good excuse to do it. For now just "do as you see" in the code without obsessing too much about it, we can just fix it later when we I add the `clang-format` config.

**Comment by ltjax** [comment]
Well, to be honest I have a more a more egoistical reason too. I've embedded lager into my app and when I change something, my editor (VS2017) automatically reformats the lager file according to my root-project's clang-format config, since lager does not have its own.
There does not seem to be an option to blacklist/whitelist certain folders in the clang-format plugin yet, so the plugin is to blame here. But having an own clang-format file would solve my option and doing "the big reformat" early in the project history is probably better than doing it later.

**Comment by arximboldi** [comment]
This has been done a while ago :smile:
