### ISSUE TITLE
Integrate a React type reconciliation algorithm

### ISSUE THREAD

**Issue by lehmanju** [arximboldi/lager#48]
To use common UI libraries that are not value based you have to signal them when and how to update.

Maybe it is possible to implement the React way of adapting these two by describing state as a tree and by implementing their diffing algorithm (https://reactjs.org/docs/reconciliation.html).

I noticed in the documentation that a kind of adapter between state and UI was planned anyway.

Specifically I am trying to use this library in a GTK application. But I do not want to pass the state along the whole widget tree manually and check for changes before redrawing as I think it would be possible to automate this.

**Comment by arximboldi** [comment]
Hi!

There are different layers to that. On one extreme, one could make one react-style adaptor for Gtk to write the whole UI in a declarative way (I have some ideas on how to do that, but have not implemented them.)

On the other hand, one can already do some level of diffing and fine grained listening to the value based model using a new module called `cursors`. The documentation is still WIP, but there is a talk where I talk about them:

https://www.youtube.com/watch?v=e2-FRFEx8CA

**Comment by arximboldi** [comment]
Nice! I am glad that this solved your issues. Hopefully I will document the cursors API soon so it will be a bit more easy to find all this stuff.

Also, glad to hear that this is useful for Xournalpp! I use that program regularly to annotate the scanned bills that I send to my accountant, great work! Looking forward to see how that ends up looking in code.

Btw, not sure how obvious this is from the talk, but you can actually mix the Redux parts with cursors too. The `store` type now is a `reader` cursor, so you can use a tree of readers/lenses to feed updates back to the Gtk UI and it's components, and pass to these components also modularized `context<[action types...]>` to dispatch actions to keep the model update logic in Redux world. That is actually I am using the library in practice most often these days in my real world projects.

**Comment by lehmanju** [comment]
Thanks for that additional information.

Could I contact you via Gitter (we also have a Xournalpp chatroom there https://gitter.im/xournalpp/xournalpp), Matrix, IRC, or sth else if I have questions? As nobody of us has any experience with this pattern I am certain we will have some questions regarding your library. It would be really helpful if you could answer them directly instead of me opening an issue every time ;).

**Comment by arximboldi** [comment]
Cool, thanks! You can also find me in the C++ slack or by email if you wanna. Even though actually issues are nice since they create certain form of documentation :)
