### ISSUE TITLE
Lower standard to C++14

### ISSUE THREAD

**Issue by ltjax** [arximboldi/lager#5]
C++17 support is not widely available yet. As a compromise, use 17 only in the optional parts.

**Comment by ltjax** [comment]
I'm good with that. 

Note entirely sure about CMake. I've in the past used different standards in different sub-folders and that seemed to work.

**Comment by hvariant** [comment]
You can use [this](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html) to set the C++ standard in CMake.

**Comment by arximboldi** [comment]
As the library develops, more and more features are requiring C++17, but also C++17 is becoming widely available. Marking as won't fix for now.
