### ISSUE TITLE
How to use custom event loops?

### ISSUE THREAD

**Issue by lehmanju** [arximboldi/lager#50]
I am a little bit confused how event loops work in this library.

Specifically our application event flow would be something like this:
- GtkEvents are dispatched on the gtk event loop
- events are parsed into actions and dispatched
- reducing and updating state can theoretically be asynchronous as long as event ordering from the gtk loop is preserved
- rerendering just triggers an asynchronous rerender signal which leads to querying and redrawing on the gtk draw thread

As we will provide pen/touch input there shouldn't be much of a delay when translating pointer movements to state changes.

**Comment by lehmanju** [comment]
Specifically we would basically overlay render when drawing and as soon as the pen lifts off the surface we commit this to the model.

**Comment by lehmanju** [comment]
Created following struct now:
```
#pragma once

#include <functional>

#include <gdk/gdk.h>

struct with_gtk_event_loop {
private:
    struct _callback_wrapper {
        template <typename Fn>
        explicit _callback_wrapper(Fn fn): cb(std::forward(fn)) {}

        std::function<void()> cb;
    };

    template <typename Fn>
    void async(Fn&& fn) {
        throw std::runtime_error{"not implemented"};
    }

    template <typename Fn>
    void post(Fn&& fn) {
        gdk_threads_add_idle(reinterpret_cast<GSourceFunc>(callback), new _callback_wrapper{std::forward(fn)});
    }

    void pause() {}
    void resume() {}
    void stop() {}

private:
    static bool callback(_callback_wrapper* wrapper) {
        wrapper->cb();
        delete wrapper;
        return false;
    }
};
```

**Comment by arximboldi** [comment]
> Do I have to wrap everything in immer::box to prevent copying the common parts?

If you use plain structs and then `immer::vector` and `immer::map` etc things are already quite fast to copy. You can add `immer::box` around some of the structs if you see in the profiler that you spend a lot of time copying them, but often a flatter data model actually provides better cache locality and simple structs are fast to copy.

> Created following struct now:

That event look integration looks fine. I am not familiar enough with GTK to know if there is a better way to do it. One note, the call to `std::forward` is missing `std::forward<Fn>` (the `<Fn>` part is important.)

**Comment by arximboldi** [comment]
Note that this event loop integration calls things in the main thread, you can also do a multi-threaded setup as you suggest in the opening post. However, I would suggest to go like this for now, once the value-based design is in place, it will be easy to move to the multi-thread setup.

(One way, for example, would be to use `boost::asio`, there is already a wrapper in the Lager repostiory. You can just launch a thread with an `io_context`, or a `thread_pool` with a `strand` for the `store`, etc. Then you use `watch()` on the store and in the handler send the new state to the UI thread.)
