### ISSUE TITLE
Brainstorm: operators for `xform` and `zoom` (IDEAS/OPINIONS WANTED)

### ISSUE THREAD

**Issue by arximboldi** [arximboldi/lager#56]
At the moment, there are three ways you can derive a cursor:
- `operator[x]` you can pass an index or a lens
- `.zoom(lens)` you can pass a lens
- `.xform(xf [, wfx])` you can pass one or two transducers

This is alright, but I am not super fan of the `.xform()` part in particular, it leads to code like:
```cpp
data.xform(zug::map([](auto&& x) {
  // three level of parens/braces until you get to the meat
}))
```
One idea, would be to use an operator for that. For example `operator^`:
```cpp
data ^ zug::map([] (auto&& x) { ... })
     ^ zug::filter([] {auto&& x} { ... });
```
Then it would be nice to use the same syntax for indexes and lenses, then, if we used `operator/` instead, we can write:
```cpp
data / &foo::bar / 0 / or_default 
     / zug::filter([](auto&& x) { return x > 0; })
     / zug::map([](auto&& x) { 
           return std::to_string(x);
       })
```
Sadly, we can't SFINAE on transducers or lenses, because we use deduced return types all over the place when defining them. So we need a different operator for each, we can combine those two:
```cpp
data / &foo::bar / 0 / or_default 
  ^ zug::filter([](auto&& x) { return x > 0; })
  ^ zug::map([](auto&& x) { 
        return std::to_string(x);
    })
```
This works because of operator precedence, but if we put the transducers first then we would need parenthesis:
```cpp
(data
  ^ zug::filter([](auto&& x) { return x > 0; })
  ^ zug::map([](auto&& x) { 
        return std::to_string(x);
    }))
  / &foo::bar / 0 / or_default 
```
Something that, on the other hand, would be more obvious if we just forget about using a symmetric operator for lenses and stick to `operator[]`:
```cpp
(data
  ^ zug::filter([](auto&& x) { return x > 0; })
  ^ zug::map([](auto&& x) { 
        return std::to_string(x);
    }))
  [&foo::bar][0][or_default]
```
Also, instead of `operator^` or `/` we have other candidates, for example `>>` or `/` for transducers?

**Comment by Siapran** [comment]
what about just `[lens]` and `(transducer)`?

**Comment by arximboldi** [comment]
The problem with `()` is the level of nesting. You have `data(map([] { /* the meat is 3 levels deep*/ }))`.
To be honest, most of the time I just use `map()` or `filter`, so I am considering simply providing aliases for those directly in the cursor interface `data.map(...)` or `data.filter(...)`, which might be a bit more user-friendly, that way also you don't need to learn transducers for those very common and simple use-cases.

**Comment by tusooa** [comment]
Use any two infix operators that is assoc<ltr> and of same precedence (https://en.cppreference.com/w/cpp/language/operator_precedence) could solve the problem at syntax-level. Which two operators would be satisfactory at the aesthetic level is another question.

**Comment by arximboldi** [comment]
I think for now #90 should be satisfying enough.
