### ISSUE TITLE
List of child nodes can shrink during iteration.

### ISSUE THREAD

**Issue by Siapran** [arximboldi/lager#62]
https://github.com/arximboldi/lager/blob/master/lager/detail/nodes.hpp#L185

As discussed in the past, a potential fix to this is to make the list of child nodes an immutable data structure and work on a copy. This, however, means that we are pulling Immer as a dependency for Lager, which should be fine considering Lager is designed to work best with immutable data structures, and there aren't exaclty that many implementations out there...

**Comment by Siapran** [comment]
So there are two approaches to solving this:
- make `children_` an `immer` collection so `notify()` can work on a copy.
- make `garbage` into a member boolean and only clear it in `collect()`, and only call collect at the end of the outermost nested call to `notify()` (keep a `size_t notify_depth_` member to keep track of nesting depth).

I'm testing the second solution right now, and it seems to work fine, though I wouldn't trust it without going through some more rigorous testing. Using immutable collections still seems like the better idea, although performance might suffer.

**Comment by arximboldi** [comment]
I'm not against the second solution. Anyways I think this might take a revamp once we integrate data diffing in, because then we potentially need to store children in a map, not vector.
