### ISSUE TITLE
Fix edge case in lenses::bind_opt

### ISSUE THREAD

**Issue by Siapran** [arximboldi/lager#66]
https://github.com/arximboldi/lager/blob/master/lager/lenses/optional.hpp#L37

Consider the following:
```cpp
struct foo {
	optional<int> value;
};

using model = vector<foo>;

lens<model, optional<int>> first_value = at(0) | bind_opt(attr(&foo::value));

model clear_first_value(model m) {
	return set(first_value, m, nullopt);
}
```
 The `attr` lens will be bypassed, because we are writing `nullopt` back into the lifted lens. This should not be the case, because the original lens can handle `nullopt`. I need to find a solution that lets me keep most of the logic from `opt_impl` factored.

**Comment by arximboldi** [comment]
It is a bit unclear, what is your expected behavior? You want that when the parent is not empety, it sets the leaf? Or you want to always set the parent?

**Comment by Siapran** [comment]
```cpp
TEST_CASE("lenses::bind_opt fix", "[lenses][optional][bind_opt]") {
    struct foo {
        std::optional<int> value;
    };

    using model = std::vector<foo>;

    auto first_value = at(0) | bind_opt(attr(&foo::value));

    model m {{{42}}};

    CHECK(view(first_value, set(first_value, model{}, 42)) == std::nullopt);
    CHECK(view(first_value, set(first_value, m, std::nullopt)) == std::nullopt);
    CHECK(view(first_value, set(first_value, m, 43)) == 43);
}
```

Before my tentative fix, the second check would fail (setting `nullopt` would not overwrite the existing `42`)

**Comment by arximboldi** [comment]
Oh I see! Thanks!

**Comment by arximboldi** [comment]
So I can assume this is fixed now?
