### ISSUE TITLE
[build error] fatal error: 'cereal/cereal.hpp' file not found

### ISSUE THREAD

**Issue by faywong** [arximboldi/lager#67]
I find it's hard to compile pass as cereal  zug... related headers is not all-in-one.

```shell
lager/lager/debug/cereal/struct.hpp:23:10: fatal error: 'cereal/cereal.hpp' file not found
#include <cereal/cereal.hpp>
```

**Comment by faywong** [comment]
because i missed the nix deps step? I will try nix first on my linux workstation later.

**Comment by arximboldi** [comment]
Hi!

On Linux, Nix will get you working.

Note that Zug is the only critical dependency. Cereal is only needed if you use the `debug` module, which is optional. Are you trying to build the tests and examples? You can disable that with `cmake -Dlager_BUILD_TESTS=no -Dlager_BUILD_EXAMPLES=no`.

**Comment by faywong** [comment]
> Hi!
> 
> On Linux, Nix will get you working.
> 
> Note that Zug is the only critical dependency. Cereal is only needed if you use the `debug` module, which is optional. Are you trying to build the tests and examples? You can disable that with `cmake -Dlager_BUILD_TESTS=no -Dlager_BUILD_EXAMPLES=no`.

Thx. Got it.
