### ISSUE TITLE
Inconsistency between "Genericity" in doc and API

### ISSUE THREAD

**Issue by tusooa** [arximboldi/lager#69]
The section https://sinusoid.es/lager/modularity.html#dealing-with-underlying-effects has code:
```
       [&] (DocumentAction a) {
           auto doc = static_cast<DocumentModel>(m);
           auto eff = lager::effect<DocumentAction, DocumentDeps>{lager::noop};
           lager::invoke_reducer<DocumentDeps>(r, doc, a, [&](auto e) {
               eff = e;
           });
           m.position = m.history.size();
           m.history = m.history.take(m.position).push_back(doc);
           return {m, eff};
       },
```

It calls invoke_reducer as `lager::invoke_reducer<DocumentDeps>(r, doc, a, <lambda>);` and discards its return value.
However, [API](https://sinusoid.es/lager/context.html#_CPPv2N5lager14invoke_reducerERR7ReducerRR5ModelRR6ActionRR13EffectHandlerRR15NoEffectHandler) specifies that `invoke_reducer` "returns the resulting model." These are inconsistent. 

After peeking at the [source code](https://github.com/arximboldi/lager/blob/master/lager/context.hpp#L506), it turns out that the API is consistent with it. So this call to `invoke_reducer` will *not* update the underlying model as expected.

From my point of view, a possible change would be to turn this function into:

```
       [&] (DocumentAction a) {
           auto eff = lager::effect<DocumentAction, DocumentDeps>{lager::noop};
           auto doc = lager::invoke_reducer<DocumentDeps>(r, static_cast<DocumentModel>(m), a, [&](auto e) {
               eff = e;
           });
           m.position = m.history.size();
           m.history = m.history.take(m.position).push_back(doc);
           return {m, eff};
       },
```

**Comment by arximboldi** [comment]
You are correct, I changed the API and forgot to update the documentation. Thanks a lot for the report!

Feel free to make a PR if you want the credit :slightly_smiling_face:  Otherwise I will update it myself when I find time.
