### ISSUE TITLE
How to implement aggregation?

### ISSUE THREAD

**Issue by tusooa** [arximboldi/lager#70]
Consider we have a component called `foo`, and it has

```
struct foo_model;
using foo_action = std::variant<...>;
auto update_foo(foo_model, foo_action) -> std::pair<foo_model, lager::effect<foo_action, ...>>;
```

Now we would like to have a component that holds a *list* of `foo`s:

```
using id_t = ...;
struct aggreate_model
{
    immer::map<id_t, foo_model> foos;
};
```

Intuitively, we would like to at least add, remove and update the items in the list.

The question comes in -- how to implement its actions and reducer?

Adding and removing seems simple:

```
struct add_foo { id_t id; foo_model foo; };
struct remove_foo { id_t id; };

using aggregate_action = std::variant<add_foo, remove_foo>;

auto update_aggregate(aggregate_model m, aggregate_action a)
    -> std::pair<aggreagte_model, lager::effect<aggregate_action>>
{
    std::visit(lager::visitor{...}, a);
}
```

For updating, it seems we have to uniquely identify the individual item first.

One solution might be to wrap the `foo_action` into another class that contains
the `id` of the `foo` one wants to modify, but it now becomes unclear what one
should do with effects that `update_foo` returns:

```
struct change_foo { id_t id; foo_action action; };

using aggregate_action = std::variant<add_foo, remove_foo, change_foo>;

auto update_aggregate(aggregate_model m, aggregate_action a)
    -> std::pair<aggreagte_model, lager::effect<aggregate_action>>
{
    std::visit(lager::visitor{
        ...,
        [=] (change_foo a) {
            auto foo_to_update = m.foos.at(a.id);
            auto [new_foo, eff] = update_foo(foo_to_update, a.action);
            return {
                aggregate_model{m.foos.set(a.id, new_foo)},
                // What should I do with eff?
            };
        }
    }, a);
}
```

We cannot return `eff` directly, because it is of type `lager::effect<foo_action>`,
but we want `lager::effect<aggregate_action>`, and `aggregate_action` does not have
a variant typed `foo_action` -- it only has `change_foo`, because we need to uniquely
identify `foo` with `id`.

Alternatively, we could change the `foo_action`s to let them record their `id`. However,
as the aggregation level increases, we will end up changing the most fundamental models
every time and having to record more and more `id`s. This is also far from satisfactory,
because this makes the item model (`foo`) heavily depend on the aggregation model (`aggregate`):

```
// Assume foo_action records its id
using aggregate_action = std::variant<add_foo, remove_foo, foo_action>;

auto update_aggregate(aggregate_model m, aggregate_action a)
    -> std::pair<aggreagte_model, lager::effect<aggregate_action>>
{
    std::visit(lager::visitor{
        ...,
        [=] (foo_action a) {
            auto foo_to_update = m.foos.at(a.id);
            auto [new_foo, eff] = update_foo(foo_to_update, a);
            return {
                aggregate_model{m.foos.set(a.id, new_foo)},
                eff
            };
        }
    }, a);
}
// What if we want to get an aggregation of aggregation?
struct whole_model { immer::map<id_t, aggregate_model> aggregates; };
using whole_action = std::variant<add_aggregate, remove_aggregate, aggregate_action>;

auto update_whole(whole_model m, whole_action a)
    -> std::pair<whole_model, lager::effect<whole_action>>
{
    std::visit(lager::visitor{
        ...,
        [=] (aggregate_action a) {
            auto [new_aggregate, eff] = m.aggregates.set(a.aggregate_id, update_aggregate(m.aggregates.at(a.id), a));
            return {
                aggregate_model{new_aggregate},
                eff,
            };
        }
    }, a);
}
// Now foo_action must have `foo_id` and `aggregate_id` in order for the
// context to accept that effect.
```

Does this mean that aggregation does not work well with effects?
Or is there a better approach to this problem? Thank you very much for any help.

**Comment by arximboldi** [comment]
Hi @tusooa!

It is a good question. I have indeed thought about this issue already but I think not many people bump into it because it is more common to have effects at top level in the application (load document, save document, etc) and not at fine grained level.

Automatic effect conversion works when the inner action is convertible to the outter action. When that happens, the context is convertible automatically from inner action to outer action. (Or from subset to superset).

When such automatic convertions are not possible, there is a `context<X>` constructor that takes a `context<Y>` and a convertion function `Y -> X`. This allows you to provided the necessary information to "situate" actions in a greater context.

I briefly mention this API in this part of my latest talk: https://youtu.be/SAMR5GJ_GqA?t=1463

Now, in that example we are combining draw functions. You want to combine effects. Going back to your example where you use a `change_foo` action, we can use that API to fill the gap you leave in the comment `// What should I do with eff?`

```cpp
struct change_foo { id_t id; foo_action action; };

using aggregate_action = std::variant<add_foo, remove_foo, change_foo>;

auto update_aggregate(aggregate_model m, aggregate_action a)
    -> std::pair<aggreagte_model, lager::effect<aggregate_action>>
{
    std::visit(lager::visitor{
        ...,
        [=] (change_foo a) {
            auto foo_to_update = m.foos.at(a.id);
            auto [new_foo, eff] = update_foo(foo_to_update, a.action);
            return {
                aggregate_model{m.foos.set(a.id, new_foo)},
                [eff=eff, id=a.id](auto&& ctx) {
                    eff({ctx, [id](auto a) {
                        return change_foo{id, a};
                    }});
                }    
            };
        }
    }, a);
}
```

Arguably, this could be simplified by introducing a new constructor for `effect<>` that takes the action convertion function directly. With such API, this would look like this:

```cpp
auto update_aggregate(aggregate_model m, aggregate_action a)
    -> std::pair<aggreagte_model, lager::effect<aggregate_action>>
{
    std::visit(lager::visitor{
        ...,
        [=] (change_foo a) {
            auto foo_to_update = m.foos.at(a.id);
            auto [new_foo, eff] = update_foo(foo_to_update, a.action);
            return {
                aggregate_model{m.foos.set(a.id, new_foo)},
                lager::effect<aggregate_action>{
                    eff, 
                    [id](auto a) { return change_foo{id, a}; }
                }
            };
        }
    }, a);
}
```

I leave the issue open as a reminder to add such API, it should be easy :)

Does this answer your question>

**Comment by tusooa** [comment]
Yes, thank you! That looks good.
