### ISSUE TITLE
Clang 10 and 11 cannot generate optimized code for house example

### ISSUE THREAD

**Issue by vincent-hui** [arximboldi/lager#81]
If Clang 10 or 11 is chosen to compile the house example https://godbolt.org/z/cyeawy
we can see the generated code is not as optimized as gcc counterpart.
Is it possible to change the implementation of lager so the Clang 11 can generate optimized code?

Thanks

The generated code is
```
main: # @main
  mov qword ptr [rsp - 32], offset .L.str
  mov byte ptr [rsp - 24], 0
  mov qword ptr [rsp - 16], offset .L.str.1
  mov byte ptr [rsp - 8], 0
  movups xmm0, xmmword ptr [rsp - 16]
  movaps xmmword ptr [rsp - 72], xmm0
  mov rax, qword ptr [rsp - 72]
  movaps xmmword ptr [rsp - 56], xmm0
  mov rcx, qword ptr [rsp - 32]
  mov dl, byte ptr [rsp - 24]
  mov esi, dword ptr [rsp - 23]
  movzx edi, word ptr [rsp - 19]
  mov r8b, byte ptr [rsp - 17]
  mov qword ptr [rsp - 56], rax
  mov byte ptr [rsp - 48], 1
  mov qword ptr [rsp - 104], rcx
  mov byte ptr [rsp - 96], dl
  mov dword ptr [rsp - 95], esi
  mov word ptr [rsp - 91], di
  mov byte ptr [rsp - 89], r8b
  mov rax, qword ptr [rsp - 56]
  mov qword ptr [rsp - 88], rax
  mov al, byte ptr [rsp - 48]
  mov byte ptr [rsp - 80], al
  mov eax, dword ptr [rsp - 47]
  mov dword ptr [rsp - 79], eax
  movzx eax, word ptr [rsp - 43]
  mov word ptr [rsp - 75], ax
  mov al, byte ptr [rsp - 41]
  mov byte ptr [rsp - 73], al
  movzx eax, byte ptr [rsp - 80]
  ret
.L.str:
  .asciz "kitchen"

.L.str.1:
  .asciz "bedroom"
```

**Comment by arximboldi** [comment]
The code is still inlined, you can get a bit more insight about what is going on by adding some prints to separate the different parts of the salad of "moves" https://godbolt.org/z/4sWxze

I think this is still acceptable. The read part is still optimal, but the write part seems to be creating an extra intermediate temporary, yet still everything is inline. We can give this is a try again in the future using the latest implementation in Lager, once they add Lager support into godbolt directly: https://github.com/compiler-explorer/compiler-explorer/issues/2195
